//
//  ContactInformation.h
//  JudoKitObjC
//
//  Created by Mihai Petrenco on 8/7/19.
//  Copyright © 2019 Judo Payments. All rights reserved.
//

#import <Foundation/Foundation.h>
#import "PostalAddress.h"

NS_ASSUME_NONNULL_BEGIN

/**
 * An object containing the Billing / Shipping information of the payment.
 * It is generated by ApplePayManager from a PKPayment object returned from
 * Apple Pay's delegate method.
 */
@interface ContactInformation : NSObject

/**
 * The billing / shipping email address if specified in the ApplePayConfiguration object;
 */
@property (nonatomic, strong) NSString * _Nullable emailAddress;

/**
 * The name of the person if specified in the ApplePayConfiguration object;
 */
@property (nonatomic, strong) NSPersonNameComponents * _Nullable name;

/**
 * The billing / shipping phone number if specified in the ApplePayConfiguration object;
 */
@property (nonatomic, strong) NSString * _Nullable phoneNumber;

/**
 * The billing / shipping postal address if specified in the ApplePayConfiguration object;
 */
@property (nonatomic, strong) PostalAddress * _Nullable postalAddress;


/**
 * Designated initializer
 *
 * @param emailAddress - the email address returned from a PKContact object
 * @param name - the name components returned from a PKContact object
 * @param phoneNumber - the phone number returned from a PKContact object
 * @param postalAddress - a PostalAddress object containing location information
 */
- (instancetype)initWithEmailAddress: (nullable NSString *)emailAddress
                                name: (nullable NSPersonNameComponents *)name
                         phoneNumber:(nullable NSString *)phoneNumber
                       postalAddress:(nullable PostalAddress *)postalAddress;

@end

NS_ASSUME_NONNULL_END
